# Generated by Django 4.0.1 on 2022-01-21 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.CharField(max_length=24, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('trial_id', models.UUIDField(primary_key=True, serialize=False)),
                ('track_name', models.CharField(max_length=255)),
                ('track_file', models.CharField(max_length=1024)),
                ('beat_divider', models.IntegerField()),
                ('smoothness_score', models.FloatField()),
                ('mean_velocity', models.FloatField()),
                ('autocorrelation_score', models.FloatField()),
                ('kinematics', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.UUIDField(primary_key=True, serialize=False)),
                ('session_time', models.DateTimeField()),
                ('session_score', models.FloatField()),
                ('session_mean_vel', models.FloatField()),
                ('session_autocorr_score', models.FloatField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_id', models.UUIDField(primary_key=True, serialize=False)),
                ('exercise_type', models.CharField(max_length=255)),
                ('exercise_side', models.CharField(max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.session')),
            ],
        ),
    ]
