# Generated by Django 4.1.3 on 2023-08-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_time',
            field=models.CharField(max_length=255),
        ),
    ]
